"""A content-addressed cache for LLM responses.

Two reasons, and the second is the one that matters.

**Cost.** A re-run of the same batch against the same prompt should not be billed twice.

**The pitch video does not depend on a live API.** A demo that calls a hosted endpoint in
front of a panel is a demo with a single point of failure nobody in the room controls. A
warm cache makes the run reproducible, and reproducible is also what lets a reviewer check
a number rather than take it.

THE KEY

    sha256(system + user + schema_name + prompt_version + model + thinking flag)

Every component is there because changing it changes the answer:

*   `user` carries the rendered rows, so different data is a different key.
*   `prompt_version` is `name.vN+checksum`, so **editing a prompt without bumping its
    version still invalidates the cache** -- which is the whole reason identity carries a
    checksum. Keying on the version string alone would serve answers generated by text
    that no longer exists.
*   `model` and the thinking flag change the output for identical input, so a model swap
    must not silently reuse the previous model's answers.

WHAT IS NOT CACHED

Failures. A rate limit, a transport error, a malformed response -- none of them are
stored. Caching a failure would make a transient outage permanent for as long as the cache
lives, and the retry that would have fixed it never runs.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from llm.provider import LLMRequest, LLMResponse

DEFAULT_CACHE_DIR = Path("runs") / "_llm_cache"


def cache_key(request: LLMRequest, model: str) -> str:
    digest = hashlib.sha256()
    for part in (
        request.system,
        request.user,
        request.schema_name,
        request.prompt_version,
        model,
        "thinking=1" if request.enable_thinking else "thinking=0",
    ):
        digest.update(part.encode("utf-8"))
        # A separator, so ("ab", "c") and ("a", "bc") are different keys rather than the
        # same concatenation.
        digest.update(b"\x00")
    return digest.hexdigest()


@dataclass
class CacheStats:
    hits: int = 0
    misses: int = 0
    writes: int = 0

    @property
    def hit_rate(self) -> float:
        total = self.hits + self.misses
        return self.hits / total if total else 0.0

    def as_dict(self) -> dict:
        return {
            "hits": self.hits,
            "misses": self.misses,
            "writes": self.writes,
            "hit_rate": round(self.hit_rate, 4),
        }


class ResponseCache:
    """One JSON file per key. Boring on purpose.

    A directory of files is inspectable with a text editor, survives a process crash
    mid-write of a different key, and needs no server on a reviewer's machine. The volume
    is a few thousand small files per run, which is well inside what this has to handle.
    """

    def __init__(self, directory: Path | str = DEFAULT_CACHE_DIR, enabled: bool = True) -> None:
        self.directory = Path(directory)
        self.enabled = enabled
        self.stats = CacheStats()

    def _path(self, key: str) -> Path:
        # Two-character shard, so no single directory holds every entry.
        return self.directory / key[:2] / f"{key}.json"

    def get(self, request: LLMRequest, model: str) -> LLMResponse | None:
        if not self.enabled:
            return None

        path = self._path(cache_key(request, model))
        if not path.is_file():
            self.stats.misses += 1
            return None

        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            # A truncated entry is a miss, not a crash. The call simply runs again.
            self.stats.misses += 1
            return None

        self.stats.hits += 1
        return LLMResponse(
            text=payload["text"],
            model=payload["model"],
            provider=payload["provider"],
            input_tokens=payload.get("input_tokens", 0),
            output_tokens=payload.get("output_tokens", 0),
            seconds=0.0,
            cache_hit=True,
            truncated=payload.get("truncated", False),
        )

    def put(self, request: LLMRequest, response: LLMResponse) -> None:
        """Store a successful response. Failures are deliberately not stored."""
        if not self.enabled or response.truncated:
            return

        path = self._path(cache_key(request, response.model))
        path.parent.mkdir(parents=True, exist_ok=True)

        payload = {
            "text": response.text,
            "model": response.model,
            "provider": response.provider,
            "input_tokens": response.input_tokens,
            "output_tokens": response.output_tokens,
            "truncated": response.truncated,
            # Provenance for a human reading the cache directory. Not part of the key.
            "prompt_version": request.prompt_version,
            "job": request.job,
        }

        # Write-then-rename, so a crash cannot leave a half-written entry that a later run
        # would read as a valid response.
        temporary = path.with_suffix(".tmp")
        temporary.write_text(
            json.dumps(payload, indent=2) + "\n", encoding="utf-8", newline="\n"
        )
        temporary.replace(path)
        self.stats.writes += 1
