"""Loading versioned prompts from llm/prompts/. No prompt string is written in Python.

BUILD.md: "Prompts referenced by version in the audit record. No inline prompt strings."
The reason is reproducibility. An audit record saying `parse.v1` is only useful if
`parse.v1` is a thing that can be retrieved and read; a prompt assembled from f-strings
scattered across a module cannot be retrieved at all, and the version number becomes a
label for whatever the code happened to say that day.

VERSION *AND* CHECKSUM

A declared version is not enough on its own. Editing `parse.v1` in place without bumping
the number leaves every previous audit record pointing at text that no longer exists, and
silently poisons the response cache, which is keyed on prompt identity.

So identity is `name.vN+checksum` -- `parse.v1+8f2a91c4d3e0` -- where the checksum covers
the entire file including its front-matter. An unbumped edit is then visible in the audit
trail as a different identity, and invalidates the cache correctly instead of serving
answers generated by text nobody can read any more.

FRONT-MATTER AND SECTIONS

    ---
    name: parse
    version: 1
    job: parse
    schema: ParsedNarrationBatch
    enable_thinking: false
    max_tokens: 8000
    batch_size: 20
    ---

    ## SYSTEM
    ...
    ## USER
    ... {items} ...
    ## ITEM
    ...

`## ITEM` is rendered once per input row and joined into `{items}`. Putting the per-row
format in the prompt file rather than in Python is the same rule again: how a row is
presented to the model is part of the prompt, and a change to it changes the checksum.

Front-matter is parsed by hand rather than with a YAML library. It is five scalar keys,
the format is fully specified above, and a dependency whose failure mode is "accepts
something subtly different from what you wrote" is a poor trade for saving fifteen lines.
"""

from __future__ import annotations

import hashlib
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from llm.provider import LLMRequest
from llm.schemas import json_schema_for, schema_for

PROMPT_DIR = Path(__file__).resolve().parent / "prompts"

_FRONT_MATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
_SECTION = re.compile(r"^## ([A-Z]+)\s*$", re.MULTILINE)

_REQUIRED_KEYS = ("name", "version", "job", "schema", "enable_thinking", "max_tokens", "batch_size")
_INT_KEYS = ("version", "max_tokens", "batch_size")
_BOOL_KEYS = ("enable_thinking",)


class PromptError(Exception):
    """A prompt file is malformed. Raised at load time, never mid-run."""


@dataclass(frozen=True)
class Prompt:
    name: str
    version: int
    job: str
    schema_name: str
    enable_thinking: bool
    max_tokens: int
    batch_size: int
    system: str
    user_template: str
    item_template: str
    checksum: str
    path: Path

    @property
    def version_id(self) -> str:
        """What lands in the audit record. Bumped version OR edited text both change it."""
        return f"{self.name}.v{self.version}+{self.checksum}"

    @property
    def json_schema(self) -> dict:
        return json_schema_for(self.schema_name)

    def render_items(self, items: Sequence[Mapping]) -> str:
        """One block per row, using the prompt's own ITEM template.

        `str.format` substitutes values without re-parsing them, so a narration containing
        braces is inert here. The template is ours; only the values are untrusted.
        """
        blocks = []
        for item in items:
            try:
                blocks.append(self.item_template.format(**item))
            except KeyError as exc:
                raise PromptError(
                    f"{self.path.name} ITEM template needs {exc} which the caller did not supply"
                ) from None
        return "\n".join(blocks)

    def render(self, items: Sequence[Mapping]) -> str:
        if "{items}" not in self.user_template:
            raise PromptError(f"{self.path.name} USER section has no {{items}} placeholder")
        return self.user_template.replace("{items}", self.render_items(items))

    def request(self, items: Sequence[Mapping]) -> LLMRequest:
        """Everything the provider needs, with the source rows carried alongside."""
        return LLMRequest(
            job=self.job,
            system=self.system,
            user=self.render(items),
            schema=self.json_schema,
            schema_name=self.schema_name,
            prompt_version=self.version_id,
            max_tokens=self.max_tokens,
            enable_thinking=self.enable_thinking,
            context=tuple(dict(i) for i in items),
        )

    def batches(self, items: Sequence[Mapping]) -> list[Sequence[Mapping]]:
        size = self.batch_size
        return [items[i : i + size] for i in range(0, len(items), size)]


def _parse_front_matter(text: str, path: Path) -> dict:
    match = _FRONT_MATTER.match(text)
    if match is None:
        raise PromptError(f"{path.name} has no --- front-matter block at the top")

    values: dict = {}
    for lineno, line in enumerate(match.group(1).splitlines(), start=2):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            raise PromptError(f"{path.name}:{lineno} is not `key: value`")
        key, _, value = line.partition(":")
        values[key.strip()] = value.strip()

    missing = [k for k in _REQUIRED_KEYS if k not in values]
    if missing:
        raise PromptError(f"{path.name} front-matter is missing: {', '.join(missing)}")

    for key in _INT_KEYS:
        try:
            values[key] = int(values[key])
        except ValueError:
            raise PromptError(
                f"{path.name} front-matter {key}={values[key]!r} is not an integer"
            ) from None

    for key in _BOOL_KEYS:
        lowered = str(values[key]).lower()
        if lowered not in ("true", "false"):
            raise PromptError(f"{path.name} front-matter {key}={values[key]!r} is not true/false")
        values[key] = lowered == "true"

    return values


def _parse_sections(text: str, path: Path) -> dict[str, str]:
    body = _FRONT_MATTER.sub("", text, count=1)
    parts = _SECTION.split(body)
    if len(parts) < 3:
        raise PromptError(f"{path.name} has no ## SECTION headings")

    sections = {
        parts[i]: parts[i + 1].strip() for i in range(1, len(parts) - 1, 2)
    }
    for required in ("SYSTEM", "USER", "ITEM"):
        if not sections.get(required):
            raise PromptError(f"{path.name} has no ## {required} section, or it is empty")
    return sections


def load_file(path: Path) -> Prompt:
    text = path.read_text(encoding="utf-8")
    front = _parse_front_matter(text, path)
    sections = _parse_sections(text, path)

    # Resolved here so a prompt naming a schema that does not exist fails on load, not on
    # the first live call after twenty minutes of a run.
    schema_for(front["schema"])

    return Prompt(
        name=front["name"],
        version=front["version"],
        job=front["job"],
        schema_name=front["schema"],
        enable_thinking=front["enable_thinking"],
        max_tokens=front["max_tokens"],
        batch_size=front["batch_size"],
        system=sections["SYSTEM"],
        user_template=sections["USER"],
        item_template=sections["ITEM"],
        # Whole file, front-matter included: max_tokens is part of what produced a result.
        checksum=hashlib.sha256(text.encode("utf-8")).hexdigest()[:12],
        path=path,
    )


@lru_cache(maxsize=1)
def registry() -> dict[str, Prompt]:
    """Every prompt on disk, keyed by `name.vN`. Cached; prompts do not change mid-run."""
    found: dict[str, Prompt] = {}
    for path in sorted(PROMPT_DIR.glob("*.md")):
        prompt = load_file(path)
        key = f"{prompt.name}.v{prompt.version}"
        if key in found:
            raise PromptError(
                f"two prompt files both declare {key}: "
                f"{found[key].path.name}, {path.name}"
            )
        found[key] = prompt
    if not found:
        raise PromptError(f"no prompt files found in {PROMPT_DIR}")
    return found


def load(job: str, version: int | None = None) -> Prompt:
    """The prompt for one job. Highest version unless one is pinned.

    Pinning exists so a run can be reproduced against the prompt it actually used, which
    is the point of recording the version in the first place.
    """
    candidates = [p for p in registry().values() if p.job == job]
    if not candidates:
        known = sorted({p.job for p in registry().values()})
        raise PromptError(f"no prompt for job {job!r}. Known jobs: {', '.join(known)}")

    if version is not None:
        for prompt in candidates:
            if prompt.version == version:
                return prompt
        available = ", ".join(str(p.version) for p in sorted(candidates, key=lambda p: p.version))
        raise PromptError(f"no v{version} of {job!r}; available: {available}")

    return max(candidates, key=lambda p: p.version)
