"""What a human decision actually stores, and whether two decisions can be told apart.

This file exists because the audit trail has now been wrong on the live path twice, and
neither time did a test catch it. Both escapes share a shape: the code that writes to
Postgres is not the code that runs when Postgres is absent, and the suite runs without
Postgres. A test that exercises the fallback proves nothing about the path that runs in
production -- it proves the opposite of what it appears to prove, because it goes green
while the real path is broken.

So the guard below reads the SQL rather than executing it. It needs no database, which
means it runs on every machine and in every CI job, which is the only property that would
have caught either defect.

The round-trip test underneath it is the demonstration, not the guard: it skips without a
database, so it can never be the thing this relies on.

WHAT WAS WRONG

The INSERT wrote `(id, run_id, layer, decision, approver, created_at)` and nothing else,
while `decision` is `escalated` for approve, reject and edit alike. The entity was never
written, so no row said which exception it was about; the verdict was never written, so no
row said what was decided. An approve on one settlement and a reject on another differed
by timestamp and by nothing else.

`input_row_hashes` was the sharpest of them. It is a column on the table, the payload has
always populated it, and it was still dropped -- so the hash tying a decision to the exact
source row it saw was computed and thrown away on every approval.

The file fallback wrote the whole payload the entire time. **The degraded path stored more
than the healthy one**, which inverts what a fallback is for.
"""

from __future__ import annotations

import re
import uuid
from pathlib import Path

import pytest

from api.review import ACTIONS, record_decision
from ledgerloop.audit import DECISION_ESCALATED, LAYER_MODEL, AuditRecord, row_hash
from ledgerloop.models import AuditRecord as AuditRow
from llm.codes import ReasonCode

REPO_ROOT = Path(__file__).resolve().parents[1]
REVIEW_PY = REPO_ROOT / "api" / "review.py"

# Generated by the database on insert, so absent from the payload by design.
GENERATED = {"id", "created_at"}


def _insert_columns() -> set[str]:
    """The column list of the INSERT into audit_records, read out of the source.

    The statement is assembled from adjacent string literals, so the quotes and the line
    breaks between them are removed before matching. Parsed rather than executed on
    purpose: see this module's docstring.
    """
    source = REVIEW_PY.read_text(encoding="utf-8")
    flat = re.sub(r'"\s*\n\s*"', "", source)  # join adjacent literals
    match = re.search(
        r"INSERT INTO audit_records\s*\(([^)]*)\)\s*VALUES", flat, re.I | re.S
    )
    assert match, "no INSERT INTO audit_records found in api/review.py"
    return {c.strip().strip('"') for c in match.group(1).split(",") if c.strip()}


def _human_decision_payload() -> dict:
    """The record a human approval builds, exactly as `record_decision` builds it."""
    record = AuditRecord(
        run_id="a-run",
        layer=LAYER_MODEL,
        decision=DECISION_ESCALATED,
        entity_id="pay_000000000005",
        reason_code=ReasonCode.LOW_CONFIDENCE,
        reason_detail="human approve",
        input_row_hashes={"settlement": row_hash("pay_000000000005")},
        approver="a-person",
    )
    payload = record.as_row()
    payload["action"] = "approve"
    return payload


def test_the_insert_stores_every_field_the_record_carries_and_the_table_can_hold() -> None:
    """If a decision carries a value and there is a column for it, it must be written.

    Asserted as an invariant over the payload and the table rather than as a list of the
    columns that happen to matter today. The defect this replaces was four fields dropped
    silently; a test naming those four would go green the next time a fifth is added and
    forgotten, which is the same failure one field later.

    Fields with no column are not required -- `reason_detail` and `batch_dir` have nowhere
    to go. Fields the payload leaves empty are not required either: a human approval has no
    feature vector and no token cost, and writing NULLs into those columns would assert
    nothing.
    """
    payload = _human_decision_payload()
    columns = {c.name for c in AuditRow.__table__.columns}
    written = _insert_columns()

    carried = {
        k
        for k, v in payload.items()
        if k in columns and k not in GENERATED and v not in (None, "", {}, [])
    }

    missing = sorted(carried - written)
    assert not missing, (
        f"the INSERT drops {missing}: the record carries these and audit_records has a "
        f"column for each, so they are computed and then thrown away. An audit row that "
        f"omits them records that somebody decided something, which is the one thing an "
        f"audit trail cannot be allowed to mean"
    )


def test_the_entity_and_the_verdict_are_both_written() -> None:
    """Named explicitly, because these two are what make one decision distinguishable.

    The invariant above would also be satisfied by a table with no `entity_id` column at
    all -- `carried` is intersected with the columns that exist. That is the right rule
    for a field the schema never claimed to hold, and the wrong one for these two: losing
    them is not a gap in the record, it is the record ceasing to mean anything.
    """
    written = _insert_columns()
    for column in ("entity_id", "action", "input_row_hashes"):
        assert column in written, (
            f"audit_records.{column} is not written by the INSERT. Without entity_id no "
            f"row says which exception was decided; without action no row says what was "
            f"decided, because `decision` is 'escalated' for approve and reject alike"
        )


def test_decision_stays_escalated_so_a_human_verdict_is_not_an_auto_match() -> None:
    """The verdict got its own column rather than being written into `decision`.

    `decision` answers what the pipeline did with the row. Filing an approval as `matched`
    would let a human decision be counted in the auto-match rate -- the number the whole
    thesis rests on -- so the two facts stay in two columns.
    """
    payload = _human_decision_payload()
    assert payload["decision"] == DECISION_ESCALATED
    assert payload["action"] == "approve"
    assert payload["decision"] != payload["action"]


def test_the_action_column_refuses_a_verdict_outside_the_closed_set() -> None:
    """The database enforces the same set the application validates against.

    An application check is a promise; a constraint is a guarantee, and it holds against
    someone typing into psql.
    """
    constraint = next(
        (
            c
            for c in AuditRow.__table__.constraints
            if getattr(c, "name", "") == "ck_audit_records_action_enum"
        ),
        None,
    )
    assert constraint is not None, "audit_records has no CHECK constraint on action"
    text = str(constraint.sqltext).lower()
    for action in ACTIONS:
        assert f"'{action}'" in text, f"{action!r} missing from the action constraint"


# --------------------------------------------------------------- the round trip

def _database_available() -> bool:
    """Reachable, not merely configured.

    Deliberately not `if DATABASE_URL is set`: the documented local setup is
    `docker compose up`, which exposes Postgres on the default host URL without anyone
    exporting anything. Gating on the variable would skip this on the machine most likely
    to be able to run it. The connect is bounded by `ledgerloop.db.CONNECT_TIMEOUT`, so an
    absent database costs seconds rather than hanging the suite.
    """
    try:
        from sqlalchemy import text

        from ledgerloop.db import engine

        with engine().begin() as conn:
            conn.execute(text("select 1"))
        return True
    except Exception:
        return False


@pytest.mark.skipif(not _database_available(), reason="no reachable DATABASE_URL")
def test_an_approve_and_a_reject_are_distinguishable_in_the_table() -> None:
    """The demonstration: two verdicts on two exceptions, read back and told apart.

    A skipping test cannot be the guard -- the guards above do that job without a
    database. This one proves the guards are asserting something real.
    """
    from sqlalchemy import text

    from ledgerloop.db import engine

    run_id = f"audit-trail-test-{uuid.uuid4().hex[:8]}"
    approved = "pay_000000000005"
    rejected = "pay_000000000006"

    first = record_decision(
        run_id=run_id, entity_id=approved, action="approve", approver="ann",
        batch_dir="data/test", run_counts={"settlements": 1, "matched": 0, "exceptions": 1},
    )
    second = record_decision(
        run_id=run_id, entity_id=rejected, action="reject", approver="raj",
        batch_dir="data/test", run_counts={"settlements": 1, "matched": 0, "exceptions": 1},
    )
    assert first["stored_in"] == "postgres", first["detail"]
    assert second["stored_in"] == "postgres", second["detail"]

    with engine().begin() as conn:
        rows = conn.execute(
            text(
                "SELECT entity_id, action, approver, input_row_hashes, decision "
                "FROM audit_records WHERE run_id = :run_id ORDER BY created_at"
            ),
            {"run_id": run_id},
        ).mappings().all()

    assert len(rows) == 2, f"expected two rows for {run_id}, got {len(rows)}"
    by_entity = {r["entity_id"]: r for r in rows}

    assert set(by_entity) == {approved, rejected}, (
        "the rows do not name the two exceptions they were about"
    )
    assert by_entity[approved]["action"] == "approve"
    assert by_entity[rejected]["action"] == "reject"
    assert by_entity[approved]["approver"] == "ann"
    assert by_entity[rejected]["approver"] == "raj"

    # The hash ties each decision to the row it saw, and the two differ.
    hashes = [r["input_row_hashes"]["settlement"] for r in rows]
    assert hashes[0] == row_hash(approved)
    assert hashes[1] == row_hash(rejected)
    assert hashes[0] != hashes[1]

    # And the property the separate column exists to protect.
    assert {r["decision"] for r in rows} == {DECISION_ESCALATED}
