"""initial schema

Revision ID: 0001
Revises: 
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('calibration_method', sa.String(length=32), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('training_batch', sa.String(length=512), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_dir', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('mock_llm', sa.Boolean(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_auto_matched', sa.Integer(), nullable=False),
    sa.Column('rows_exception', sa.Integer(), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_reconciled', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.CheckConstraint('rows_total >= 0', name='ck_runs_rows_total_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('layer', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('input_row_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calibrated_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('token_cost_inr', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('approver', sa.String(length=128), nullable=True),
    sa.CheckConstraint('calibrated_confidence IS NULL OR (calibrated_confidence >= 0 AND calibrated_confidence <= 1)', name='ck_audit_confidence_is_a_probability'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_run_id'), 'audit_records', ['run_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proposed_journal_entry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_reason_code'), 'exceptions', ['reason_code'], unique=False)
    op.create_index(op.f('ix_exceptions_run_id'), 'exceptions', ['run_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exception_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approver', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('edited_journal_entry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("action IN ('approve', 'reject', 'edit')", name='ck_approvals_action_enum'),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_exception_id'), 'approvals', ['exception_id'], unique=False)
    # ### end Alembic commands ###

    # Architecture rule 5: audit records are append-only. Keeping no UPDATE or DELETE path
    # in application code is a promise; this trigger is a guarantee, and it holds against
    # anyone reaching past the ORM with raw SQL. CREATE OR REPLACE keeps it idempotent,
    # which matters because the entrypoint runs "alembic upgrade head" on every start.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ledgerloop_audit_is_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_records is append-only: % is not permitted on this table',
                TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute("DROP TRIGGER IF EXISTS trg_audit_records_append_only ON audit_records;")
    op.execute(
        """
        CREATE TRIGGER trg_audit_records_append_only
        BEFORE UPDATE OR DELETE ON audit_records
        FOR EACH ROW EXECUTE FUNCTION ledgerloop_audit_is_append_only();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_records_append_only ON audit_records;")
    op.execute("DROP FUNCTION IF EXISTS ledgerloop_audit_is_append_only();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_exception_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_exceptions_run_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_reason_code'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_audit_records_run_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_table('runs')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
